version:  '2.3'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  adminer:
    image: adminer
    restart: on-failure
    ports:
    - '8080:8080'

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './symfony/public/:/usr/src/symfony'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - '.:/usr/src/symfony'
    user: ${LOCAL_USER}